import React from 'react';
import Head from 'next/head';
import Header from './componentes/Header';

export default function Home() {
  return (
    <>
      <Head>
        <title>TRACTIAN | Monitoramento online de ativos e gestão da manutenção</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="">
        <Header />
      </main>

    </>
  );
}
