import React from 'react';
import Head from 'next/head';
import Header from './componentes/Header';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>TRACTIAN | Monitoramento online de ativos e gestão da manutenção</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main className="">
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        main
      </main>

      <footer className="">
        footer
      </footer>
    </div>
  );
}
