import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Header from './componentes/Header';
import Banner from './componentes/Banner';
import Servicos from './componentes/Servicos';
// import ondas from '../../imagens/ondas.svg';

export default function Home() {
  return (
    <>
      <Head>
        <title>TRACTIAN | Monitoramento online de ativos e gestão da manutenção</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="w-full relative">
        <Header />
        <Banner />
        {/* <Image src={ondas} className="bg-gradient-to-l from-black to-gray-800" /> */}

        <Servicos />
      </main>
    </>
  );
}
